accountsync.php

Eileen, I'm not exactly sure how you plan using connector_id's, so please treat this PR as a place-holder for an issue rather than a fix.
What I was finding was that when I create a CiviCRM contribution, the civicrm_account_contact record was created with connector_id set to NULL. The Push job was looking for records with connector_id set to '0' (zero). This change sets the connector_id column to zero when a row is created.
I was tempted to make a change to the API that checked whether connector_id was set, but wondered whether that might be too late. As this bit of code knew about connector_id it seemed the place to change. The CiviXero extension may need to change as well, unless it is the API that needs changing (eg, the REST call for "Queue sync to Xero" on the contact summary screen …

Set connector_id to 0

---

accountsync.php

Eileen,
When testing the merging of duplicate CiviCRM contacts, the account_contact 'delete' (accountsync.php, line 538) was throwing an exception as the $params needed to include elements for 'id', 'plugin' and 'connector_id'. In addition, when doing the account_contact 'create' on line 540 I found I needed to unset $accountContact['id'] so the 'create' did a 'create' rather than an 'edit'.
So this PR is a suggestion to remove the 'delete' on line 538.
What that means is that rather than creating a new account_contact with the same details as the one that was deleted, this change would simply update the existing account_contact with the $new_id.
It seems to work, but is there a side-effect I'm ignoring?

When deduping contacts, there is no need to delete account_contact

---

CRM/Accountsync/BAO/AccountInvoice.php

When pushing an Invoice to Xero, the code fails if the Contribution's Payment Instrument is not set.
This happens in the case when an online contribution is made to "Pay later".
This change simply catches the exception from the CiviCRM API and does nothing.
This is satisfactory for Invoices, since they don't use the 'payment_instrument_accounting_code' value. Some further work may be needed for Bank Transactions, which do use it.

Handle case when the Payment Instrument is not set

---

accountsync.php
settings/AccountSync.setting.php

Adds a configuration option to allow contributions made via configured payment processors to be excluded from invoice creation.

Optionally skip for payment processors

---

CRM/Accountsync/Job/job.mgd.php
accountsync.php

As part of a project to support a different accounting package we've implemented a system using CiviCRM's hook utilities that allows you to specify the plugin(s) available to accountsync.  Currently it lets you use multiple at the same time, which may need to be addressed.

Implement plugin mechanism

---

CRM/Accountsync/BAO/AccountInvoice.php
settings/AccountSync.setting.php

See issue at https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/issues/22

Add preference to allow override of receipting options for completed contributions

---

accountsync.php

As `_accountsync_get_skip_invoice_create_entities` uses this param, need to pass it on to the function.

missing connector_id param

---

CRM/Accountsync/Upgrader.php

Previous update sets the default values for `account_status_id` to 0, but the existing one remains to be NULL.

Change existing NULL status to 0

---

accountsync.php

This avoids $0 contribution to enter `civicrm_account_invoice` table.

Prevent zero contribution to create account invoice

---

accountsync.php
settings/AccountSync.setting.php

We found $objectRef containing total amount but not its value while updating the contribution. As, we already fetch status from api, this changes check `total_amount` with the same.

Avoid invalid status to create invoices

---

accountsync.php

**Steps to reproduce the issue**
1. Create a contact in CiviCRM, which adds an entry into civicrm_account_contact table. 
2. Delete this contact before is is synced with Xero.
3. Extension deletes the previous entry and adds a new one into the table. 
4. Now when we run a schedule job it syncs the deleted contact into Xero.
**Expected behaviour**
When contact is getting deleted and extension should not add new entry into the table.
**Solution**
Check if the contact is deleted or not, if it is deleted skip the Contact sync in __accountsync_create_account_contact_ hook.

CIVIXERO-6: Prevent adding contact new record into civicrm_account_contact table for soft deleted contacts.

---

accountsync.php

1. Create a contribution page with Pay Later option enabled.
2. Contribution should have the financial type of Member Dues
3. Submit new contribution via Test-Drive link
Notice the contribution is added in account_invoice table which syncs the data with any of the available plugins.
Added **is_test** to get returned and checking it's value along with **total_amount**. If **is_test** is true we skip the particular Contribution.

CIVICRM-870: Skip contrition to get added in account_invoice table if it's a test contribution.

---

CRM/Accountsync/BAO/AccountInvoice.php

CiviCRM contribution status is not changed to cancelled when the linked Xero invoice status is changed to voided.
1. Create a contribution in CiviCRM
2. Mark the contribution as completed in CiviCRM
3. Sync the contribution with Xero
4. Change the status of the invoice in Xero to voided
5. Sync the change to CiviCRM
6. Check the status of the contribution, it is still completed
This is because AccountInvoice.update_contribution API Update contribution status to cancelled for only pending contributions.

CIVIXERO-15: Cancel contributions regardless of it's status.

---

CRM/Accountsync/BAO/AccountInvoice.php

See [CiviXero issue 45](https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/issues/45) for an explanation.
This change moves the call to CRM_Financial_BAO_FinancialTypeAccount::getInstrumentFinancialAccount() into the try/catch block which surrounds the following code, so if the payment_instrument_id is unset the ensuing exception is handled locally rather than stopping CiviXero pushing this invoice to Xero.
This change has been tested for the following 2 cases:
1. a Pending contribution has no payment instrument
2. a recurring PayPal Standard contribution has no payment instrument for the second and subsequent contributions (this is probably a bug with that payment processor)
In both these cases the CiviXero push invoice job successfully pushes the invoices to Xero.

CiviXero Invoice push fails if contribution has no payment_instrument_id

---

CRM/Accountsync/BAO/AccountInvoice.php

Overview
------------
Let's assume we've 10 contributions in the system and their statues needs to updated because they are paid in any Invoicing software (e.g. Xero) 
First contribution picked by  **completeContributionFromAccountsStatus** function has some issues and **completetransaction**  API throws an exception. This exception is not handled in the function because of that rest of the contributions are skipped. 
Expected Behaviour
------------
If there is some issue with the contribution, We should log the error in DB and skip particular contribution and continue with rest of the contributions.
Solution
------------
Implemented a try/catch block to catch the exception thrown by **completetransaction** api and the error is stored into the DB for admin to review. 
_Agileware Ref: …

Fixed completeContributionFromAccountsStatus to continue execution even if one contribution fails.

---

CRM/Accountsync/BAO/AccountInvoice.php

This one's apparently been broken for over 2 years, but only recently came up for one of our clients.
The code to override whether CiviCRM should send a receipt is checking the wrong variable – `$isSendReceipt` is not a number.  Here is a fix.

CIVIXERO-33: Fix variable check to override sending receipt.

---

Civi/Hooks/SearchKitTasks.php
managed/contact_errors.mgd.php

* Add "Contact ID" column to contact errors display.
* Rename / add search tasks:
* Re-queue -> retry sync (and add "is_error_resolved=true" - otherwise you can't tell that you've marked them for retry).
* Dismiss error -> mark as resolved
* Do not sync: New one to mark that you don't want to sync.
Both "re-queue" and "dismiss error" confused me and my clients and they also didn't quite work properly!

Add contactID to contact errors. Add/rename actions

---

CRM/Accountsync/BAO/AccountInvoice.php
api/v3/AccountInvoice.php

I've been having problems on one site where invoices appear to be being sent twice. According to the code it was set to "no_override" in accountsync so it should be doing whatever it's set to. But it's definitely sending an invoice and not a receipt.
First step to troubleshooting is changing from Contribution.completetransaction to Payment.create which is what this PR does.

Switch to Payment.create, use pseudoconstants, simplify receipt handling

---

CRM/Accountsync/BAO/AccountInvoice.php
accountsync.php
api/v3/AccountInvoice.php

@eileenmcnaughton some straightfoward fixes/improvements pulled from my fork.
* Add spec to API3 AccountInvoice.update_contribution
* Performance: skipCleanMoney
* Add accounts_contact_id to getderived using contribution contact_id
* Remove unused code (that breaks getderived because financial_type_id is not returned by default in API3 contribution.get) - this was causing getderived to fail silently.
* Log exceptions in getderived - if getderived fails actually log something...
* Fix https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/issues/75 0 (unknown) is a valid accounts status for invoice - tested and confirmed that this is an appropriate fix.

Improvements / fixes

---

ang/accountsync/EditCtrl.js
api/v3/AccountContact.php
tests/phpunit/api/v3/AccountContactTest.php
tests/phpunit/bootstrap.php

one of @mattwire's commits - I'm curious as to whether I can get tests to run
https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/commit/9511c5fdf3342bda6c1b886154258932b9ffc219

 Handle existing contact_id in account_contact table when matching 

---

accountsync.php

I've implemented a function to "Create Invoice in CiviCRM" if it does not exist on Xero Invoice Pull in my fork of civixero. But there is a problem because this hook *always* fires and creates an AccountInvoice entry as soon as we call "Contribution::Create" and then we end up with two records in AccountInvoice - one containing CiviCRM contact ID and one containing Xero accounts_invoice_id.
Changing the below parameter stops the new record being created and the existing one updates automatically to map contribution_id to accounts_invoice_id.
@eileenmcnaughton Any thoughts on a better way to do this?
(see https://github.com/mjwconsult/nz.co.fuzion.civixero/commit/f1db1a516b48deb99d647809d93a92d7c8107609#diff-ae8087fabc2278332d47c7a8c20ef96d456517ae2f3ecde0f4a3c8e8ac10139aR164)

Allow to not create a new AccountInvoice entry (a bit hacky)

---

accountsync.php

The following error is thrown on some sites during extension DB upgrades. 
> /var/www/default/htdocs/httpdocs/profiles/compuclient/modules/contrib/civicrm/ext/nz.co.fuzion.accountsync/accountsync.php).
> null given in array_merge() (line 65 of	
> TypeError: array_merge(): Argument #2 must be of type array, null given in array_merge() (line 65 of /var/www/default/htdocs/httpdocs/profiles/compuclient/modules/contrib/civicrm/ext/nz.co.fuzion.accountsync/accountsync.php).
> WD php: TypeError: array_merge(): Argument #2 must be of type array,     [error]

Fix array merge error due to empty entities
